sudo: false
env:
  global:
    secure: CVxKUE9U5U8sn3EYOy4JPp045bjZivuFPG5cjz3Ozdbad9sCaGpeZdqkVour9MqRADSl+JSTU9FKHHeJu9m8i2/z+HOygkimRq00y+CKYJ4MDLsddd/fyJuS8OEMVg/QfR4nLYuCPy7sU3Kuq3BRKRXLr4JzfevCTAKQG+1+0Tg=

language: node_js
node_js:
- '0.10'

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install --quiet -g grunt-cli karma bower
- npm install
- bower install

script: grunt

after_success: "./deploy/post_build.travis.sh"
